services:
  api:
    build:  ./api
    ports:
      - "8080:8080"
    volumes:
      - ./api:/api
    environment:
       ENV: development
  web:
    build: ./backend
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/usr/src/app
    depends_on:
      - api



