apiVersion: apps/v1
kind: Deployment
metadata:
  name: moviestore
spec:
  replicas: 1
  selector:
    matchLabels:
      app: moviestore
  template:
    metadata:
      labels:
        app: moviestore
    spec:
      containers:
      - image: registry.cloud.okteto.net/anitaachu/go-moviestore:golang
        env:
        - name: POSTGRES_CONNECTION
          valueFrom:
            secretKeyRef:
              name: db-creds
              key: connection

---

apiVersion: v1
kind: Service
metadata:
  name: moviestore
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: ClusterIP  
  ports:
  - name: "moviestore"
    port: 8080
  selector:
    app: moviestore
    
 ---
 apiVersion: v1
 kind: Secret
 metadata:
  name: db-creds
 type: Opaque
 data:
  connection: cG9zdGdyZXNxbDovL2RvYWRtaW46eGIxZHpwazE2bmllb3g1M0Bhbml0YS1wb3N0Z3Jlc3FsLWRvLXVzZXItNzkyODEzOC0wLmIuZGIub25kaWdpdGFsb2NlYW4uY29tOjI1MDYwL2RlZmF1bHRkYj9zc2xtb2RlPXJlcXVpcmU=
